### ISSUE TITLE
Exposed API Key

### ISSUE THREAD

**Issue by vtsman** [WilliXL/PyPoser#10]
I couldn't help but notice that you left your MonkeyLearn API key in your committed program. Even though you're probably using a free demo of MonkeyLearn, and the consequences of doing so are minimal, I'd recommend that you store your key in an external file and add that file to your .gitignore. Even if it's not immediately impactful, it's still a good habit to get into.

**Comment by WilliXL** [comment]
Hey thanks for noticing that. I kinda just sloppily slapped my code into a repo for submission purposes.
